ifneq ($(filter $(BOARD_TOUCHSCREEN_FOCALTECH), FT8006AN),)
obj-y += focaltech_upgrade_ft8006s_an.o
else ifneq ($(filter $(BOARD_TOUCHSCREEN_FOCALTECH), FT8009),)
obj-y += focaltech_upgrade_ft8009.o
else
obj-y += focaltech_upgrade_ft8006s_aa.o
endif
